---
- hosts: all
  become: yes
  tasks:
  - name: Setup apt-get for the package installation of the .NET Core
    copy: dest=/etc/apt/sources.list.d/dotnetdev.list owner=root
      content="deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main"
  - name: Install cryptographic keys
    shell: apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - name: Update Ubuntu sources
    apt: update_cache=yes
  - name: Install Dependencies
    apt: name={{ item }} state=present
    with_items:
      - mono-runtime  # Mono (Open source Dot Net framework)
      - dotnet-sharedframework-microsoft.netcore.app-1.0.0 # Dot Net Dependencies
  - name: Install Dot Net
    apt: name=dotnet-dev-1.0.0-preview2-003121 state=present
  - name: Add aliases for easier navigation/running
    lineinfile:
      dest=/home/vagrant/.bashrc
      line={{ item }}
    with_items:
      - alias goapp="cd /home/vagrant/WebApplication1/src/WebApplication1"
      - alias runapp="goapp && dotnet run"
  - name: Add WebApplication1
    unarchive: src=WebSite/WebApplication.tar.gz dest=/home/vagrant/
  - name: Add all dotnet application dependencies
    shell: dotnet restore
    become_user: vagrant
    args:
      chdir: /home/vagrant/WebApplication1/src/WebApplication1
      creates: project.lock.json
